### ISSUE TITLE
The other logos also need to be changed

### ISSUE THREAD

**Issue by bgette** [emvi/xbegone#1]
When loading the website and favicon.
![image](https://github.com/emvi/xbegone/assets/64483377/3631049b-2a1b-4475-8d21-a76a1b703cb4)
![image](https://github.com/emvi/xbegone/assets/64483377/6cf20b60-2210-4c92-90e9-41a98aff0664)

**Comment by bgette** [comment]
the problem is here ig
![image](https://github.com/emvi/xbegone/assets/64483377/2787efb8-c08c-4de3-91cd-69f7d48c3684)

**Comment by Kugelschieber** [comment]
Hey! I've fixed the manifest version. The favicon should already be replaced. I didn't tinker with the loading icon yet.
